version: "3"

services:
  api-server:
    image: springboot-app:local
    command: bash
    tty: true
    stdin_open: true

    ports:
      - 5000:5000

    volumes:
      - ./api-server:/home/ubuntu/api-server

    working_dir: /home/ubuntu/api-server

    build:
      dockerfile: ./dockerfiles/springboot-app.Dockerfile

  inference-server:
    image: ai-runtime:local
    command: bash
    tty: true
    stdin_open: true
    
    ports:
      - 50051:50051 

    working_dir: /home/ubuntu/inference-server

    volumes:
      - ./inference-server:/home/ubuntu/inference-server

    build:
      dockerfile: ./dockerfiles/ai-runtime.Dockerfile
   

  web-server:
    image: web-server:local
    volumes:
      - ./web-server/html:/usr/share/nginx/html
      - ./web-server/nginx:/etc/nginx

    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80

    ports:
      - 8080:80 

    build:
      dockerfile: ./dockerfiles/web-server.Dockerfile

