version: "3"

services:
  api-server:
    image: api-server:local
    command: bash
    tty: true
    stdin_open: true

    volumes:
      - ./api-server:/root/api-server
    ports:
      - 5000:5000

    build:
      dockerfile: ./dockerfiles/api-server.Dockerfile

  inference-server:
    image: inference-server:local
    command: bash
    tty: true
    stdin_open: true

    volumes:
      - ./inference-server:/root/inference-server

    build:
      dockerfile: ./dockerfiles/inference-server.Dockerfile
      
   

  web-server:
    image: web-server:local
    volumes:
      - ./web-server:/usr/share/nginx/html
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80

    build:
      dockerfile: ./dockerfiles/web-server.Dockerfile

