version: "3"

services:
  terraform: 
    image: cjswosa2/terraform:0.0.1
    volumes:
      - ./:/root
    
    build: 
      dockerfile: ../dockerfiles/terraform.Dockerfile


    env_file:
      - .env
