version: "3"

services:
  terraform: 
    image: terraform:local
    volumes:
      - ./:/home

    build: 
      dockerfile: ../dockerfiles/terraform.Dockerfile

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

    env_file:
      - .env
